name: Zig ARM64 Linux 3.x Static (via zig-bootstrap)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential git cmake python3 curl \
          qemu-user-static binfmt-support \
          musl-tools ninja-build g++ unzip xz-utils

    - name: Clone zig-bootstrap
      run: |
        git clone https://github.com/ziglang/zig-bootstrap
        cd zig-bootstrap
        git checkout master

    - name: Build Zig for ARM64 Linux 3.x (Cortex-A53)
      run: |
        cd zig-bootstrap

        ./build --release \
          --target aarch64-linux-musl \
          --cpu cortex_a53 \
          --strip \
          --out zig-aarch64-linux3x

    - name: Test Zig binary via QEMU (Cortex-A53)
      run: |
        qemu-aarch64 -cpu cortex-a53 zig-bootstrap/zig-aarch64-linux3x/bin/zig version

    - name: Package Zig binary
      run: |
        cd zig-bootstrap
        tar -cJf zig-aarch64-linux3x.tar.xz zig-aarch64-linux3x

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zig-aarch64-linux3x
        path: zig-bootstrap/zig-aarch64-linux3x-0.14.1.tar.xz
