name: Build Zig Static ARM64

on:
  workflow_dispatch:

jobs:
  build-zig:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git cmake ninja-build python3 \
            build-essential curl musl-tools \
            g++-aarch64-linux-gnu

      - name: Checkout Zig
        uses: actions/checkout@v4
        with:
          repository: ziglang/zig
          ref: 0.14.1

      - name: Clone musl-cross-make
        run: |
          git clone https://github.com/richfelker/musl-cross-make.git
          cd musl-cross-make
          echo "TARGET = aarch64-linux-musl" > config.mak
          echo "OUTPUT = /opt/musl-cross" >> config.mak
          make -j$(nproc)

      - name: Build Zig statically with musl for ARM64
        run: |
          export PATH="/opt/musl-cross/bin:$PATH"
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-linux-musl-gcc \
            -DCMAKE_EXE_LINKER_FLAGS="-static" \
            -DZIG_STATIC=ON \
            -DCMAKE_BUILD_TYPE=Release
          ninja

      - name: Upload Zig Binary
        uses: actions/upload-artifact@v4
        with:
          name: zig-aarch64-musl
          path: build/zig
