name: Build Zig Static ARM64

on:
  workflow_dispatch:

jobs:
  build-zig:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git cmake ninja-build python3 \
            build-essential curl \
            patchelf tree llvm-19 clang-19 lld-19 \
            libclang-19-dev liblld-19-dev llvm-19-dev

          echo "/usr/lib/llvm-19/bin" >> $GITHUB_PATH

      - name: Download musl-cross toolchain (aarch64-unknown-linux-musl)
        run: |
          curl -L -o aarch64-unknown-linux-musl.tar.xz https://github.com/cross-tools/musl-cross/releases/download/20250520/aarch64-unknown-linux-musl.tar.xz
          tar -xf aarch64-unknown-linux-musl.tar.xz
          echo "$PWD/aarch64-unknown-linux-musl/bin" >> $GITHUB_PATH

      - name: Build zlib (for aarch64-musl)
        run: |
          curl -LO https://zlib.net/zlib-1.3.1.tar.gz
          tar xf zlib-1.3.1.tar.gz
          cd zlib-1.3.1
          CC=aarch64-unknown-linux-musl-gcc \
          ./configure --static --prefix=$GITHUB_WORKSPACE/sysroot
          make -j$(nproc)
          make install

      - name: Build zstd (for aarch64-musl)
        run: |
          git clone --depth=1 https://github.com/facebook/zstd
          mkdir -p zstd/build_output
          cd zstd/build_output
          cmake ../build/cmake \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-unknown-linux-musl-gcc \
            -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/sysroot \
            -DZSTD_BUILD_STATIC=ON \
            -DZSTD_BUILD_SHARED=OFF \
            -DZSTD_BUILD_PROGRAMS=OFF
          make -j$(nproc)
          make install

      - name: Checkout Zig 0.14.1
        run: |
          git clone --branch 0.14.1 --depth 1 https://github.com/ziglang/zig
          mkdir zig/build

      - name: Build Zig for aarch64-musl
        working-directory: ./zig/build
        run: |
          cmake .. -G Ninja \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-unknown-linux-musl-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-unknown-linux-musl-g++ \
            -DCMAKE_EXE_LINKER_FLAGS="-static" \
            -DCMAKE_BUILD_TYPE=Release \
            -DZIG_STATIC=ON \
            -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/sysroot
          ninja

      - name: Package zig binary
        run: |
          cd zig/build
          mkdir zig-aarch64
          cp zig zig-aarch64/
          tar -cJf zig-aarch64-linux-musl.tar.xz zig-aarch64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zig-aarch64-linux-musl
          path: zig/build/zig-aarch64-linux-musl.tar.xz
