name: Build Zig Static ARM64

on:
  workflow_dispatch:

jobs:
  build-zig:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git cmake ninja-build python3 \
            build-essential curl \
            patchelf tree libz-dev libzstd-dev

      - name: Download musl-cross toolchain (aarch64-linux-musl)
        run: |
              curl -L -o aarch64-unknown-linux-musl.tar.xz https://github.com/cross-tools/musl-cross/releases/download/20250520/aarch64-unknown-linux-musl.tar.xz
              #echo "76f0d71893f3864e91ad09feff71a719cdf94cccd4f14cc25d7deed395968b5b5b790099e49bf89756f612b  aarch64-unknown-linux-musl.tar.xz" > checksum.sha256
              #cat checksum.sha256
              #sha256sum -c checksum.sha256
              tar -xf aarch64-unknown-linux-musl.tar.xz
              echo "$PWD/aarch64-unknown-linux-musl/bin" >> $GITHUB_PATH
              #echo "$PWD/aarch64-unknown-linux-musl/bin" >> $GITHUB_ENV
     
              #tree -a .
      
      - name: Install LLVM
        run: |
            sudo apt update
            sudo apt install -y llvm-19 clang-19 lld-19
            echo "/usr/lib/llvm-15/bin" >> $GITHUB_PATH
            #which llvm-config

      - name: Checkout Zig 0.14.1
        run: |
          git clone --branch 0.14.1 --depth 1 https://github.com/ziglang/zig
          cd zig
          mkdir build

      - name: Build Zig for aarch64-musl
        working-directory: ./zig/build
        run: |
          cmake .. \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-unknown-linux-musl-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-unknown-linux-musl-g++ \
            -DCMAKE_EXE_LINKER_FLAGS="-static" \
            -DCMAKE_BUILD_TYPE=Release \
            -DZIG_STATIC=ON \
            -DZIG_USE_CCACHE=OFF
          ninja

      - name: Package zig binary
        run: |
          cd zig/build
          mkdir zig-aarch64
          cp zig zig-aarch64/
          tar -cJf zig-aarch64-linux-musl.tar.xz zig-aarch64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zig-aarch64-linux-musl
          path: zig/build/zig-aarch64-linux-musl.tar.xz
